<?php

namespace Database\Seeders;

use App\Models\Position;
use Illuminate\Database\Seeder;

class PositionSeeder extends Seeder
{
    public function run(): void
    {
        $positions = [
            'Accounting Services',
            'Administrative Aide I',
            'Administrative Aide I (Crafts & Trade Helper)',
            'Administrative Aide I (Laborer I)',
            'Administrative Aide I (Utility Worker I)',
            'Administrative Aide II',
            'Administrative Aide II (Bookbinder I)',
            'Administrative Aide III',
            'Administrative Aide III (Carpenter I)',
            'Administrative Aide III (Clerk I)',
            'Administrative Aide III (Driver I)',
            'Administrative Aide III (Laborer II)',
            'Administrative Aide III (Plumber I)',
            'Administrative Aide III (Utility Worker II)',
            'Administrative Aide IV',
            'Administrative Aide IV (Accounting Clerk I)',
            'Administrative Aide IV (Clerk II)',
            'Administrative Aide IV (Electrician I)',
            'Administrative Aide IV (Fiscal Clerk I)',
            'Administrative Aide IV (Human Resource Management Aide)',
            'Administrative Aide IV (Mechanic I)',
            'Administrative Aide IV (Stenographer I)',
            'Administrative Aide IV (Storekeeper I)',
            'Administrative Aide VI',
            'Administrative Aide VI (Accounting Clerk II)',
            'Administrative Aide VI (Clerk III)',
            'Administrative Aide VI (Communication Equipment Operator II)',
            'Administrative Aide VI (Mechanic II)',
            'Administrative Aide VI (Motorpool Dispatcher)',
            'Administrative Assisitant III',
            'Administrative Assisitant III (Storekeeper III)',
            'Administrative Assistant',
            'Administrative Assistant II',
            'Administrative Assistant II (Accounting Clerk III)',
            'Administrative Assistant II (Bookkeeper I)',
            'Administrative Assistant II (Budgeting Assistant)',
            'Administrative Assistant III (Senior Bookkeeper)',
            'Administrative Officer I',
            'Administrative Officer I (Records Officer I)',
            'Administrative Officer II',
            'Administrative Officer II (Accountant II)',
            'Administrative Officer II (Budget Officer I)',
            'Administrative Officer II (Information Officer I)',
            'Administrative Officer II (Management and Audit Analyst I)',
            'Administrative Officer III',
            'Administrative Officer III (Cashier II)',
            'Administrative Officer IV',
            'Administrative Officer IV (Administrative Officer II)',
            'Administrative Officer IV (Supply Officer II)',
            'Administrative Officer V',
            'Administrative Officer V (Budget Officer III)',
            'Agri Extension Services',
            'Agricultural Technologist',
            'Agriculturist I',
            'Agriculturist II',
            'Assessment Clerk I',
            'Assessment Clerk II',
            'Assistant Registration Officer',
            'Assistant Statistician I',
            'AutoCad Operation',
            'Backhoe Operator',
            'Barangay / Sports Coordination',
            'Barangay Assistance Aide',
            'Barangay Coordination',
            'Barangay Coordinator',
            'Barangay Health Aide',
            'Barangay Peacemaking Aide',
            'Board Secretary II',
            'Board Secretary III',
            'Bookkeeper I',
            'Building Inspection Services',
            'Buyer II',
            'Caretaking Service',
            'CCTV Operator',
            'Cemetery Caretaker',
            'Clerical Service',
            'Collection Service',
            'Communication-In-Charge',
            'Community Affairs Assistant I',
            'Community Affairs Assistant II',
            'Community Affairs Officer I',
            'Community Affairs Officer II',
            'Community Empowerment Facilitator',
            'Computer Maintenance Technologist I',
            'Computer Operator',
            'Computer Programmer I',
            'Construction Aide',
            'Construction and Maintenance Foreman',
            'Contact Tracing Aide',
            'Cooking Services',
            'Counseling Services',
            'Courier Services',
            'Database Manager',
            'Day Care Worker I',
            'Day Care Worker II',
            'Dental Aide',
            'Dentist II',
            'Dentist III',
            'Draftsman I',
            'Draftsman II',
            'Driving Services',
            'Eco Aide',
            'Economist I',
            'Electrical Services',
            'Electrician I',
            'Emergency Response Service',
            'Emergency Response Supervisor',
            'Enforcement Service',
            'Enforcer',
            'Engineer I',
            'Engineer II',
            'Engineer III',
            'Engineering Aide',
            'Engineering Assistance',
            'Engineering Assistant',
            'Engineering Services',
            'Engineering Supervision Service',
            'Environmental Management Specialist I',
            'Environmental Management Specialist II',
            'Executive Adviser',
            'Executive Assistant I',
            'Executive Assistant II',
            'Executive Assistant III',
            'Executive Assistant IV',
            'Facilities Maintenance Coordinator',
            'Financial Analyst',
            'Fire Aide',
            'Garbage Collection',
            'Gardening Aide',
            'General Service Assistance',
            'General Service Assistant',
            'GIS Operation',
            'Ground Marshall',
            'Groundskeeper',
            'Handyman Services',
            'Health Aide Service',
            'Health Education And Promotion Officer',
            'Heavy Equipment Helper',
            'Heavy Equipment Operation',
            'Heavy Equipment Operator I',
            'Heavy Equipment Operator II',
            'Heavy Equipment Operator III',
            'Helper',
            'Housekeeping Service',
            'Houseparent Service',
            'Human Resource Management Assistant',
            'Human Resource Management Officer II',
            'Human Resource Management Officer III',
            'Information Officer I',
            'Internal Auditor II',
            'IP Coordinator',
            'Isolation Unit Custodian',
            'IT Assistance',
            'Kitchen Assistance',
            'Laboratory Aide',
            'Landscaping Services',
            'LEDIPO',
            'Librarian I',
            'Librarian Services',
            'License Officer I',
            'Life Saver',
            'Light Equipment Operator I',
            'Local Assessment Operation Officer I',
            'Local Disaster Risk Reduction Management Assistant',
            'Local Disaster Risk Reduction Management Officer',
            'Local Disaster Risk Reduction Management Officer I',
            'Local Disaster Risk Reduction Management Officer II',
            'Local Disaster Risk Reduction Management Officer III',
            'Local Enfocer',
            'Local Legislative Staff Assistant I',
            'Local Revenue Collection Officer I',
            'Local Revenue Collection Officer II',
            'Logistics-In-Charge',
            'MAC Auxiliary',
            'Maintenance Aide',
            'Management & Audit Analyst II',
            'Market Inspector I',
            'Market Supervisor II',
            'Meat Inspection Service',
            'Meat Inspector I',
            'Mechanic Aide',
            'Mechanic II',
            'Media Production Aide',
            'Medical Officer',
            'Medical Officer II',
            'Medical Officer III',
            'Medical Service',
            'Medical Technologist',
            'Medical Technologist II',
            'Medtech Service',
            'MGADH I (Assistant Municipal Engineer)',
            'MGADH I (Special Operations Officer IV)',
            'MGAHD I (Assistant Municipal Health Officer)',
            'MGDH I (Municipal Health Officer)',
            'MGDH I (Municipal Planning And Development Coordinator)',
            'Midwife I',
            'Midwife II',
            'Midwife III',
            'Midwifery Services',
            'Motorpool Dispatcher',
            'Municipal Accountant',
            'Municipal Administrator I',
            'Municipal Agricultural Officer',
            'Municipal Agriculturist',
            'Municipal Assessor Officer',
            'Municipal Assistant Department Head I',
            'Municipal Budget Officer',
            'Municipal Civil Registrar Officer',
            'Municipal Councilor',
            'Municipal Engineer',
            'Municipal Government Assistant Department Head I',
            'Municipal Government Department Head I',
            'Municipal Government/Assistant Department Head I',
            'Municipal Health Officer',
            'Municipal Mayor',
            'Municipal Social Welfare & Development Officer',
            'Municipal Treasurer',
            'Municipal Vice - Mayor',
            'Nozzle Operator',
            'Nurse',
            'Nurse II',
            'Nurse III',
            'Nursing Service',
            'Nutrition Officer I',
            'Nutrition Program Aide',
            'Pharmacist',
            'Pharmacist II',
            'Pharmacy Assistance',
            'Pharmacy Services',
            'Physician',
            'Planning Officer III',
            'Population Program Officer I',
            'Population Program Worker II',
            'Project Development Assistant I',
            'Project Development Officer I',
            'Project Development Officer III',
            'Project Engineer',
            'Project Engineering Services',
            'Project Monitoring',
            'Purchasing Assistance',
            'Radiological Technologist I',
            'Record Officer I',
            'Recorder',
            'Registration Officer II',
            'Revenue Collection Clerk II',
            'Road Grader Operation',
            'Road Roller Operation',
            'Sangguniang Bayan Member',
            'Sangguniang Bayan Member (ABC President)',
            'Sangguniang Bayan Member (IP Representative)',
            'Sangguniang Bayan Member (Youth Representative)',
            'Sanitation Inspector II',
            'Sanitation Inspector III',
            'Sanitation Inspector V',
            'Secretary to the Sanggunian',
            'Sector Representative',
            'Security Agent I',
            'Security Guard I',
            'Security Guard II',
            'Security Officer I',
            'Security Officer II',
            'Security Service',
            'Senior Administrative Assistant I (Buyer V)',
            'Senior Administrative Assistant III (Private Secretary II)',
            'Senior Environment Management Specialist',
            'Senior Labor & Employment Officer',
            'Sewing Assistance',
            'Sewing Instructor Assistant',
            'Sewing Mechanic',
            'Slaughtering Assistant',
            'Social Welfare Aide',
            'Social Welfare Assistant',
            'Social Welfare Officer I',
            'Social Welfare Officer II',
            'Social Welfare Officer III',
            'Special Disbursing Officer',
            'Sports Coordinator',
            'Statistician Aide',
            'Statistician I',
            'Store Keeper',
            'Storekeeping',
            'Street Sweeper',
            'Supervising Agriculturist',
            'Supervising Nurse Service',
            'Surveying Service',
            'Tailoring Instruction',
            'Tax Mapper I',
            'Tax Mapping Aide',
            'Technical Assistance',
            'Tire Repair Service',
            'Tour Guide Service',
            'Tourism Operations Officer I',
            'Traffic Aide Service',
            'Traffic Education And Instruction',
            'Traffic Supervision Services',
            'Utility',
            'Veterinarian I',
            'Watchman Service',
            'Welder I',
            'Welding Service',
            'Writing Services',
            'Youth Coordination',
        ];

        foreach ($positions as $title) {
            Position::firstOrCreate(['title' => $title]);
        }
    }
}
